import React from 'react'
import MyWorksComponenet from '../components/MyWorksComponenet'


export const metadata = {
    title: "FINANCIA | MY WORKS PAGE",
    description: "Generated by create next app",
  };
  
const page = () => {
  return (
    <>
        <MyWorksComponenet />
    </>
  )
}

export default page