import React from 'react'
import MyWorksComponenet from '../components/MyWorksComponenet'
import TransitionProvider from '../components/TransitionProvider';
import MyWorkTransitionProviderComponent from '../components/MyWorkTransitionProviderComponent';


export const metadata = {
    title: "FINANCIA | MY WORKS PAGE",
    description: "Generated by create next app",
  };
  
const page = () => {
  return (
    <MyWorkTransitionProviderComponent>
        <MyWorksComponenet />
    </MyWorkTransitionProviderComponent>
  )
}

export default page