import ForgotPasswordCompanyComponent from '@/app/components/ForgotPasswordCompanyComponent';
import ResetPasswordComponent from '@/app/components/ResetPasswordComponent';
import TransitionProvider from '@/app/components/TransitionProvider';
import React from 'react'


export const metadata = {
    title: "FINANCIA | RESET PASSWORD PAGE",
    description: "Generated by create next app",
};
  

const page = () => {
  return (
    <TransitionProvider>
        <ResetPasswordComponent/>
    </TransitionProvider>
  )
}

export default page