import React from 'react'
import LoginComponent from '../components/LoginComponent'
import TransitionProvider from '../components/TransitionProvider';

export const metadata = {
  title: "FINANCIA | LOGIN PAGE",
  description: "Generated by create next app",
};


const page = () => {
  return (
    <TransitionProvider>
        <LoginComponent/>
    </TransitionProvider>
  )
}

export default page