import React from 'react'
import LoginComponent from '../components/LoginComponent'

export const metadata = {
  title: "FINANCIA | LOGIN PAGE",
  description: "Generated by create next app",
};


const page = () => {
  return (
    <>
        <LoginComponent/>
    </>
  )
}

export default page