import React from 'react'
import PortfolioComponent from '../components/PortfolioComponent'
import TransitionProvider from '../components/TransitionProvider';

export const metadata = {
  title: "FINANCIA | PORTFOLIO PAGE",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <TransitionProvider>
        <PortfolioComponent/>
    </TransitionProvider>
  )
}

export default page