import React from 'react'
import PortfolioComponent from '../components/PortfolioComponent'

export const metadata = {
  title: "FINANCIA | PORTFOLIO PAGE",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
        <PortfolioComponent/>
    </>
  )
}

export default page