import React from 'react'
import ForgotPasswordCompanyComponent from '../components/ForgotPasswordCompanyComponent'


export const metadata = {
  title: "FINANCIA | FORGOT PASSWORD PAGE",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
        <ForgotPasswordCompanyComponent />
    </>
  )
}

export default page