import ResetPasswordforCompanyComponent from '@/app/components/ResetPasswordforCompanyComponent';
import TransitionProvider from '@/app/components/TransitionProvider';
import React from 'react'


export const metadata = {
    title: "FINANCIA | RESET PASSWORD PAGE",
    description: "Generated by create next app",
};
  

const page = () => {
  return (
    <TransitionProvider>
        <ResetPasswordforCompanyComponent/>
    </TransitionProvider>
  )
}

export default page