import ResetPasswordforCompanyComponent from '@/app/components/ResetPasswordforCompanyComponent';
import React from 'react'


export const metadata = {
    title: "FINANCIA | RESET PASSWORD PAGE",
    description: "Generated by create next app",
};
  

const page = () => {
  return (
    <>
        <ResetPasswordforCompanyComponent/>
    </>
  )
}

export default page