import React from 'react'
import ForgotPasswordComponent from '../components/ForgotPasswordComponent'

export const metadata = {
  title: "FINANCIA | FORGOT PASSWORD PAGE",
  description: "Generated by create next app",
};


const page = () => {
  return (
    <>
        <ForgotPasswordComponent/>
    </>
  )
}

export default page