import React from 'react'
import RegisterComponent from '../components/RegisterComponent'

export const metadata = {
  title: "FINANCIA | REGISTER PAGE",
  description: "Generated by create next app",
};


const page = () => {
  return (
    <>
        <RegisterComponent/>
    </>
  )
}

export default page